### PR TITLE
switch to tcp and Delete Everything I Can

### PR DESCRIPTION
**Pull request by dominictarr**
made this as a pr to my own pr for clarity

### CODE REVIEW

**Comment by pfraze** [comment]
looks good, but travis failed

**Comment by dominictarr** [comment]
okay but you :+1: that you don't need any of this stuff?

**Comment by pfraze** [comment]
yeah

**Comment by dominictarr** [comment]
@pfraze passing! it was just a require('connect') that I forgot to delete... gonna merge this into the other pr then

**Pull request merged**
